name: Compile TODO Comments

on: push

jobs:
  compile-todo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract TODO comments
      run: |
        # Extract all TODO comments into a file, excluding todo.yml file in /.github/workflows
        grep -r -E --exclude={TODO.md,/.github/workflows/todo.yml} 'TODO' . | while read line; do
          todo="$(echo $line | cut -d ':' -f 2- | sed 's/TODO/- [ ]/')"
          echo "$todo" >> TODO.md
        done
  
    - name: Commit TODO file
      uses: EndBug/add-and-commit@v4
      with:
        add: 'TODO.md'
        message: 'Update TODO.md file'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
